import '../globals.css';
import { ReactNode } from 'react';
import { Locale, getLocale } from '@/locale';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    const locales = getLocale();
    return locales.map((locale) => ({ locale }));
}

interface IProps {
    children: ReactNode;
    params: { locale: Locale };
}

const RootLayout = ({ children, params }: IProps) => {
    return (
        <html lang={params.locale}>
            <body>{children}</body>
        </html>
    );
};

export default RootLayout;
